### ISSUE TITLE
Typelevel membership for Squants

### ISSUE THREAD

**Issue by garyKeorkunian** [typelevel/general#10]
- Squants is the Scala API for Quantities, Units of Measure and Dimensional Analysis.
- Squants provides an API and DSL that supports type safe dimensional analysis.
- All types are immutable
- The roadmap includes support for generic numerics (work in progress) to be followed by a spire-squants binding project to support high-precision dimensional analysis.
- Squants supports the Typelevel Code of Conduct.

See:  http://squants.org

**Comment by InTheNow** [comment]
Hi @garyKeorkunian 

I've done a fair amount of work in this area, please also see https://github.com/typelevel/general/issues/2 for banana-rdf application. 

NASA created an ontology for [QUDT](http://www.qudt.org/)  and [related concepts](http://www.linkedmodel.org/). This is now part of [SYSML](http://issues.omg.org/issues/task-force/SYSML14-34) and an ISO standard. I believe banana-rdf was instrumental in this work, too.

So, does squants support this? And either way, would you be interested in changing squants to be "Ontology compatible"? (Most likely by code generation). I guess the main point here is project overlap. I actually did the scalajs port of spire with this in mind.

Please note that not all of QUDT is visible in the links above - it is large and very complete.

**Comment by tpolecat** [comment]
Sorry, I wasn't watching this repo so I missed the issue being opened. We use Squants in our pure code and it really helps with type safety. So :+1: from me.

**Comment by garyKeorkunian** [comment]
Hi @InTheNow,

Thanks for the tip.  I was not aware of QUDT, but will begin looking into it.

**Comment by InTheNow** [comment]
@garyKeorkunian If you start looking into detail ,you will probably find a bunch of other "things" too.... eg [what is OWL](https://www.w3.org/TR/owl2-primer/), RDF... and as such it might be best if I or someone else go through this with you, assuming you don't already know. Its also reasonable to say its a can of worms, too.... ( eg how to serialize quant data? XSDData types with [refined](https://github.com/fthomas/refined), OWL also has real/rational number types (that could be implemented by spire) and so on).

 Also see https://github.com/banana-rdf/banana-rdf/issues/232 and the links in "SEE". @NicolasRouquette  in that issue is the same Nicolas from the qudt/NASA/sysml links above, btw. 

But briefly, there is already (somewhere) the work to do general numerics, using spire/refined/XSD Datatypes/banana-rdf (plus some extra OWL support)/shapeless/etc. With this, plus QUDT via squants, we have a _full_ solution, not just in scala, but also messaging and in the data storage layer. 

On my part, this/next week is totally off-limits. 

That said, this issue is about getting squants into Typelevel. So my main question was perhaps, "Are you interested into seeing how squants could be extended using other Typelevel libs, as well as spire, ?"  You appear to have said yes, so :+1:  from me.

**Comment by garyKeorkunian** [comment]
@InTheNow A high level briefing would be great, whenever you have the time.

I can definitely see the value in creating additional extensions - or a comprehensive binding project - to this end.

Thanks!

**Comment by InTheNow** [comment]
:+1:

**Comment by larsrh** [comment]
I for one would be happy to have a typed quantity API. Integration with spire would really be neat. What say you, @non?

**Comment by garyKeorkunian** [comment]
ping ...

**Comment by milessabin** [comment]
Sorry about the delay on this. I think criteria for incubator membership have been met now.

I'll make this a last call and then we can set the wheels in motion.

**Comment by non** [comment]
:+1: Sorry I missed this thread. I totally support incubator membership for Squants!

**Comment by larsrh** [comment]
Now on the website: typelevel/typelevel.github.com#97.
