### ISSUE TITLE
Typelevel membership for Finch

### ISSUE THREAD

**Issue by milessabin** [typelevel/general#3]
+ Finch is a thin layer of purely functional basic blocks atop of Finagle for building composable REST APIs.
+ Finch supports the Typelevel code of conduct.

See https://github.com/finagle/finch.

**Comment by milessabin** [comment]
Tagging @travisbrown.

**Comment by milessabin** [comment]
:+1:

**Comment by travisbrown** [comment]
I don't know if I should vote since I'm a Finch maintainer, but here's a :+1: from me, and a few other pieces of information:

* Finch has been using Shapeless for [request reader](https://github.com/finagle/finch/pull/246) and [router](https://github.com/finagle/finch/pull/270) composition since April of this year, and the most recent release depends on Cats.
* The initial motivation for [Circe](https://github.com/travisbrown/circe) (another Typelevel project) was to support more idiomatic and performant JSON encoding / decoding in Finch, and the two projects are well integrated (on the Finch side).
* We know of about a dozen organizations using Finch in production.

And some resources:

* [Video of a talk](https://twitter.com/vkostyukov/status/677253958188969984) by @vkostyukov (Finch's creator) from Scala Exchange last week.
* [Early slide deck by me](https://meta.plasm.us/slides/finagle/finch-and-friends/) about Finch, Cats, and Shapeless.
* [Slides by me](https://meta.plasm.us/slides/finagle/finch-and-shapeless/) about Finch, Shapeless, and Circe.

**Comment by InTheNow** [comment]
:+1:

**Comment by ImLiar** [comment]
:+1:

**Comment by ivanyu** [comment]
:+1:

**Comment by mandubian** [comment]
:+1:

**Comment by ivanyu** [comment]
:+1:

**Comment by vkostyukov** [comment]
What's worth, I'm (as a second Finch maintainer) also voting for Finch joining Typelevel.

**Comment by milessabin** [comment]
The [criteria and process](https://github.com/typelevel/general/blob/master/governance/membership.md) are still somewhat in flux, but I would say that Finch pretty clearly meets the conditions for Typelevel Incubator membership.

**Comment by larsrh** [comment]
Consensus is clear. Once the new website is live, I'm going to write down the steps required to add the project to the site, and then we can close this.

**Comment by non** [comment]
:+1:

**Comment by larsrh** [comment]
Sorry for the delay. PR to add it to the website is pending: typelevel/typelevel.github.com#91.
