### ISSUE TITLE
How we make tough decisions

### ISSUE THREAD

**Issue by rossabaker** [typelevel/general#43]
So far, Typelevel has governed itself by general agreement.  This has worked with little acrimony on issues like incubator applications, where two meritorious alternatives can both be accepted.  It was discussed in Philadelphia that more difficult decisions will come.  With #42, that day may be here.
1. Is it time to adopt a formal voting system?
2. What voting system do we use?
3. Who gets to vote?  Is it always the same set when we vote?

**Comment by rossabaker** [comment]
My own opinions:

1. Yes
2. The [Schulze Method](https://en.wikipedia.org/wiki/Schulze_method) is widely adopted in other software organizations
3. This is the hard one.  I prefer a broadly inclusive franchise without risk of being overrun by a flash mob of those who don't share Typelevel's mission, and I'm not sure how to achieve that.

**Comment by tpolecat** [comment]
One idea would be to have a voting roll initially populated by anyone who has ever had a PR merged into a Typelevel project; then let anyone add their name via PR. This would sweep up most of the active members and then allow anyone else to enroll with a minimal effort. I'm kind of hoping that this would be enough to discourage gaming the system, or at least make it hard enough that potential trolls would lose interest.

**Comment by ShaneDelmore** [comment]
I don't meet this criteria as my PRs have been merged into Scalac base, not TypeLevel, but I agree it seems like a reasonable idea.  Seems I need to get off of my butt and make a PR into TypeLevel directly soon.

**Comment by tpolecat** [comment]
Sorry, to clarify I mean anyone can add their name to the list by submitting a PR *adding their name to the list*. So you don't have to be a project contributor.

**Comment by milessabin** [comment]
I don't have quite the same sense of urgency about adopting a formal scheme ... I think in the case of #42 we'll be able to reach a decision by informal consensus. Nevertheless, it's important that we have a policy in place before we do actually have a decision to make which requires it.

The Schulze Method is a good suggestion ... it's a little elaborate, but the fact that it's used by other similar software organisations is in it's favour. It has some nice formal properties, but bear in mind that it's vulnerable to tactical voting. The far bigger problem is (3) ... futzing about with the details of the mechanics of voting schemes is completely irrelevant where the voting population is fluid.

I think @tpolecat's suggestion is good for difficult decisions where we don't expect any deliberate attempt at manipulation. If there is an expectation of an attempt at manipulation, then I think restricting the voting population to contributors makes sense.

So I think we should rank our decision making mechanisms from most desirable/typical to least typical as,

1. Consensus (which might involve informal polling).
2. A formal scheme (eg. Schulze) with an open population.
3. A formal scheme with only contributors as participants.

I think it will be relatively clear when consensus can't be reached, perhaps less clear whether 2 or 3 would be more appropriate. I think it should be the responsibility of the core/contact group (#16) to make that decision on a case by case basis.

And just to reiterate ... I believe that the vast majority of decisions should be made by consensus rather than a formal vote.

**Comment by rossabaker** [comment]
Well said.  I raise this to prepare for a failure of consensus, not to wish for it.

Tactical voting is unavoidable without dictatorship (the Gibbard-Sattherthwaite Theorem).  I like Schultze's tradeoffs because its use in similar organizations makes it predictable in production.

**Comment by milessabin** [comment]
A was trying to avoid saying "Gibbard-Satterthwaite Theorem" ;-)

**Comment by rajmahendra** [comment]
may be something like by-law will be a good idea... ?

**Comment by rossabaker** [comment]
Now covered by the [charter](https://github.com/typelevel/governance/blob/main/CHARTER.md).
