### ISSUE TITLE
Frameless full membership

### ISSUE THREAD

**Issue by OlivierBlanvillain** [typelevel/general#49]
We recently a did some of work on documentation ([this](https://github.com/adelbertc/frameless/tree/master/docs/src/main/tut) is what we have do far), and are currently discussing setting up a gh-pages website to publish it. This might a good time to apply for full typelevel project membership; move the repo to `typelevel/frameless` and publish the documentation under http://typelevel.org/frameless/

**Comment by larsrh** [comment]
Here are the current full membership criteria:

* The project should exemplify pure, typeful, idiomatic functional programming. It should not be deeply rooted in things such as side-effects and mutation - put differently, it should be fairly easy for those working in pure functional code bases to bring in your library. Mutation and other side-effecting properties is not strictly forbidden, but should have a good documented reason for doing so (e.g. performance, limitation of the language, etc.).
* Documentation for the code should (a) exist (b) be machine checked so as to enforce all documentation is up to date.
* There must be at least one active maintainer of the project who will field pull requests, issues, questions, etc.
* There much be some versioning scheme that communicate binary and/or source compatibility.

I think the first three are obviously satisfied. The fourth probably doesn't apply yet because it's still in the early 0.x stage. So, I think all criteria are met.

**Comment by larsrh** [comment]
I completely forgot about this … Sorry!

I think this can proceed. Please file a PR to the website moving the project out of the incubator.

**Comment by OlivierBlanvillain** [comment]
Awsome! Who should we bother to publish documentation under http://typelevel.org/frameless/?

**Comment by larsrh** [comment]
There are three ways to achieve something like that, ranked from "easiest" to "cumbersome":

1. move the Frameless repository to the Typelevel organisation on GitHub :+1:
2. ask me to point a `CNAME` from `frameless.typelevel.org` to @adelbertc (not quite what you want though) 😐 
3. make an unrelated Frameless repository on the Typelevel organisation and push docs there :-1:
4. push docs to the `frameless` subdirectory in the typelevel.github.com repository 😨

**Comment by OlivierBlanvillain** [comment]
First option sounds great :smile:

**Comment by larsrh** [comment]
If @adelbertc agrees I'll elevate his privileges so he can perform the move.

**Comment by adelbertc** [comment]
I'm good with the first option. We'll also want to probably change the project metadata to publish under `org.typelevel` (or something similar, perhaps `org.frameless-spark` or something of the sort) instead of `io.github.adelbertc` :-)

**Comment by larsrh** [comment]
@adelbertc You're now an owner. Please use these privileges to transfer the repository and ping me when you're done.

**Comment by adelbertc** [comment]
It looks like Gitter is experiencing issues - I'd like to do this perhaps when Gitter is up and running again both so I can give folks a heads up and also because I'm paranoid moving this while Gitter is down might cause issues with the Gitter chatroom not syncing correctly. Maybe.

**Comment by larsrh** [comment]
Gitter is back up now.

**Comment by larsrh** [comment]
Migration seems to be done now. @adelbertc, I elevated you to "admin" of the repository. All previous contributors have write privileges. You should be able to add more people if you want.

**Comment by adelbertc** [comment]
@larsrh Awesome thanks!
