### ISSUE TITLE
Use HTTPS on Typelevel web pages

### ISSUE THREAD

**Issue by ochrons** [typelevel/general#75]
Currently all typelevel.org pages are HTTP only, due to Github limitation. This can be worked around using a CDN like CloudFlare in front of Github.

Instructions: https://www.goyllo.com/github/pages/free-cloudflare-ssl-for-custom-domain/

Even if typelevel.org was hosted on a private server, it would make sense to use a CDN to speed up access from remote locations (like China, Australia, Japan, India).

**Comment by larsrh** [comment]
I have investigated this now. In general I think it's a good idea to have HTTPS. But sadly CloudFlare requires me to transfer all control of DNS to them, which I'm reluctant to do. Another possibility would be to host it not on GitHub, but on a private server.

**Comment by larsrh** [comment]
This is what Google sent me today:

![screenshot_20170818_103912](https://user-images.githubusercontent.com/923079/29451050-7d2eabee-8401-11e7-9e55-0765bc7abd92.png)

I've come to the conclusion that it's necessary to migrate to HTTPS. The self-hosting approach won't work because there are many projects that use e.g. http://typelevel.org/cats and are managed in different ways and repositories.

Hence, I'm proposing to use `typelevel.github.io` as the domain for GitHub Pages (this supports TLS) and proxy it through CloudFlare. Any opinions?

**Comment by larsrh** [comment]
There is an alternative service (Netlify) that doesn't require me to yield control of the DNS for the whole domain. I'll be deploying this now.

**Comment by larsrh** [comment]
As soon as DNS propagation is finished, https://typelevel.org should be available.
