### ISSUE TITLE
Submitting cats-mtl for typelevel incubator membership

### ISSUE THREAD

**Issue by edmundnoble** [typelevel/general#79]
This issue is for the result of https://github.com/typelevel/cats/issues/1603, the library cats-mtl which I'm submitting as a Typelevel project. cats-mtl splits out the monad transformer type classes from cats, so that they can use a different encoding of superclass relationships than cats to avoid implicit ambiguity with multiple instances of transformer type classes and avoid creating internal inconsistency within cats, as well as experiment with ways to limit the boilerplate associated with transformer class instances and decrease the number of constraints associated with said instances.

https://github.com/edmundnoble/cats-mtl

1. The only developer for now is myself.
2. I've basically copied the cats CoC mention verbatim to the README.md.
3. cats-mtl is a library for abstraction over higher-kinded types in general, which are a staple of Scala's flavor of pure FP.
4. The README.md contains motivating information about cats-mtl and some descriptions of type classes; the scaladoc above each type class explains the functionality within as well as the laws; and there is not yet any tut or doctest documentation (soon though!).

Like cats-effect the `groupId` has started as `org.typelevel`, and I've pushed artifacts to bintray for a version 0.0.1 for early adopters of cats 1.0.0-MF. Further releases should move to Sonatype like other cats offshoots.

**Comment by alexandru** [comment]
Oh man, so while I was away 1.0.0-MF was released, w00t 😁

So I'm all for cats-mtl happening, I just want to iterate my preference for a minimal-functionality strategy, at least at first.

This project is just like cats-effect and the reason for why I think cats-effect is going to be a success is because it is dependable and stable already and it does this by delivering the minimal functionality needed.

I'm interested in being a maintainer btw, if you'll agree. It's because I'm probably going to need cats-mtl down the line.

Also, thanks a lot for your effort, this is awesome.

**Comment by kailuowang** [comment]
Yah! Once the `cats-mtl` is released under the `typelevel` org, we can continue the cats `1.0.0-MF` process which is pending on a migration guide towards `cats-mtl`.

**Comment by larsrh** [comment]
Approved! Welcome & please add yourself to the [incubator](https://github.com/typelevel/typelevel.github.com/blob/development/_data/incubator.yml) list.
