### ISSUE TITLE
Proposal: Discourse setup for Typelevel projects

### ISSUE THREAD

**Issue by alexandru** [typelevel/general#89]
Not sure if this was discussed.

Gitter is not perfect for users seeking help. If a user posts a question, unless there's somebody online willing to help right then and there, it can get lost in the noise. This can also create burden on maintainers that are willing to help, but then feel the need to be always online or they might miss something. I also preferred the deep interactions people used to have on mailing lists, I'm sad that those have fallen out of favor.

The Lightbend folks now have a Discourse forum: https://discuss.lightbend.com/
Scala too: https://users.scala-lang.org/
Rust too: https://users.rust-lang.org/

It's pretty trendy. Maybe Typelevel should have one too: https://www.discourse.org/

The only problem is that somebody is going to have to host it and maintain it and unfortunately I can't offer anything in that regard. But I'm hoping somebody else will offer to do it 🙂

So can we have a `discuss.typelevel.org`?
That would be sweet.

**Comment by larsrh** [comment]
Hosting should not be a problem. But let's see first how much interest there is. Leave a thumbs-up in this issue if you think it's a good idea.

**Comment by larsrh** [comment]
... clicked "Comment" to early.

For context, two years ago, such a proposal was already rejected: #41. But maybe things have changed, so I'm happy to revisit this.

**Comment by alexandru** [comment]
Ah, should have searched before asking. I'd still prefer a Discourse instance tho.

**Comment by larsrh** [comment]
The difference between then and now is that both Scala and Lightbend have also adopted Discourse. It can't hurt to re-evaluate infrastructure choices from time to time.

**Comment by SystemFw** [comment]
> This can also create burden on maintainers that are willing to help, but then feel the need to be always online or they might miss something. 

Doesn't this double the problem? :P

Gitter is already pretty popular (although I agree it's got its limitations, primarily about archiving and searching past answers), so that means we would have to now check 3 places (github, gitter, discourse) instead of 2 (github, gitter)

**Comment by rossabaker** [comment]
As someone who has never used Discourse, what does it bring us that GitHub issues don't?  Could we solve this same problem by encouraging a culture of using issues for support as well as bugs?

**Comment by tpolecat** [comment]
I'm generally 👎 on adding another support channel. The Scala instances don't get a lot of traffic. Following them It seems to me that most things on `contributors` are design discussions that should be GH issues, and most things on `users` would work better on Gitter since they tend to start with confused users and unclear questions … I think these are better served by a quick back-and-forth. Anyway there are way more Scala users than Typelevel users and there's hardly any traffic on the Scala instances.

Re: typelevel specifically I'm on Gitter most of the day and I rarely see a question languishing. I think we do a pretty good job. The only issue is that sometimes we get the same questions over and over and it would be nice to be able to point people to answers somewhere, but I don't think discourse would solve this problem either. A more aggressively maintained cats FAQ would go a long way probably. 

I will preemptively object to adding a Wiki, in case someone was about to suggest that. 😉

**Comment by larsrh** [comment]
Seems like there's still no consensus in favour.

**Comment by alexandru** [comment]
That's fine, there needs to be consensus otherwise it can't work.
