### ISSUE TITLE
Submitting Trembita for incubator membership

### ISSUE THREAD

**Issue by vitaliihonta** [typelevel/general#93]
I'd like to propose [trembita](https://github.com/vitaliihonta/trembita) as a Typelevel incubator project.
Trembita is a project that allows to model complex data transofmation pipelines (locally, in parallel, using akka streams or on spark cluster, streaming and non-streaming). It also provides typesafe DSL for stateful transformations (FSM style like in Akka FSM actor) and QL (like frameless does but not only for spark).

It is implemented in pure-functional way (in most cases) using Cats (Effect), Shapeless, Spire.
I've already integrated it with Akka Streams, Apache Spark (RDD, SQL, Streaming).
Also I'm planning to integrate it with [distributed cache](http://infinispan.org/)
The goal of this project is to be a `glue` for techonologies zoo you see in business projects.
It also should provide easy-to-use, typesafe API.

I'm the sole maintainer.
Currently trembita doesn't support the Scala Code of Conduct because I'm developing it on my own.
I'll adopt Code of Conduct if community is interested in developing the project.
Currently there is not much documentation and tests, but I'm committed to adding more

**Comment by larsrh** [comment]
So far, this hasn't gotten any attention. Would the Frameless and/or Monix people take a look, please? @adelbertc @alexandru

**Comment by vitaliihonta** [comment]
Here is my [speech](https://youtu.be/PDBVCVv4mVc) about trembita.
Hope it will help to understand the purpose of this library 😅

**Comment by vitaliihonta** [comment]
@larsrh any updates?

**Comment by larsrh** [comment]
After leaving this open for a while, nobody from the current Typelevel project members has given this ticket a :+1:. This is required so that the technical aspects of the projects can be checked for alignment with Typelevel. Hence I'll close this for the time being. Feel free to reopen once a couple of people acknowledge the membership request. In the meantime, you could also try to solicit feedback in the [Gitter channel](https://gitter.im/typelevel/general).

**Comment by vitaliihonta** [comment]
@larsrh anyway thank you for your attention!
