### ISSUE TITLE
Governance: Should Typelevel members observe the CoC when on Twitter?

### ISSUE THREAD

**Issue by benhutchison** [typelevel/general#98]
This issue arises out of some negative, abusive & hurtful tweets posted by @travisbrown earlier this week. It started when he took exception to the [wording of a routine issue](https://github.com/travisbrown/catbird/issues/145) I raised on the catbird repo, and issued a [series of tweets](https://twitter.com/travisbrown/status/1165502986661105664), [and again](https://twitter.com/travisbrown/status/1166696404431069191), labelling me a "shithead", "asshole", "rando", "part of the reason this industry is so terrible", and implying I was a defender of white supremacists. 

In terms of content, the tweets pretty clearly don't comply with the [Typelevel CoC](https://typelevel.org/about.html). It's cyber-bullying.

What's less clear to me is the question of _jurisidiction_:  does the CoC cover the behavior of Typelevel members on Twitter and similar public forums, or just at Typelevel events, repos, chat channels etc?

I'd argue that when people accept Typelevel membership, as Travis has, then they should also accept a level of responsibility to uphold the standards and spirit of the organisation in the way they behave in public.

I'll observe that Travis' tweets were interpreted [here](https://twitter.com/fpmortals/status/1166256635452579840) as implying a more general Typelevel position, so I do think this provides evidence that Typelevel member's behavior on Twitter can & does reflect back onto the organisation.

**Comment by tpolecat** [comment]
We take reports of this nature very seriously. We will investigate and respond within 24 hours.

**Comment by milessabin** [comment]
Hi Ben, thanks for the report.

> What's less clear to me is the question of jurisidiction: does the CoC cover the behavior of Typelevel members on Twitter and similar public forums, or just at Typelevel events, repos, chat channels etc?

Strictly speaking, this occurred [outside the scope](https://typelevel.org/about.html#domain)  of the Scala Code of Conduct, however, Travis is an active maintainer of Typelevel projects and is prominent in the community, which narrows the distance.

As fellow open source maintainers we appreciate the often exhausting demands made of project owners, and understand Travis's initial frustration. Nevertheless we feel that his response was rude and disproportionate, and acknowledge that it was amplified by his considerable influence in the community. We encourage him to consider the impact of his words more carefully in the future.

On behalf of the Typelevel Steering Committee.

**Comment by travisbrown** [comment]
Ben,

I want to apologize for the name calling. I know that I can be too sensitive to what I see as entitled behavior from open source adopters, and that I can sometimes respond disproportionately. In this case I concluded that the bluntness of your request was motivated by the fact that we've disagreed on community issues in the past, and while I still suspect that that's true, I jumped to the most uncharitable interpretation too quickly.

I've not deleted any of the tweets, because I'm not trying to avoid accountability for my behavior, but if you'd like I will delete the two that include name-calling, even when it's not referring to you or anyone else specifically (e.g. the "shithead" comment).

As a final note, I don't believe I've ever engaged in any kind of name-calling or other toxic behavior in any Typelevel community channels, or in any other community or professional channels in general. If I have, I would appreciate the behavior being pointed out to me, and I'll correct it, apologize as needed, and work to do better in the future.
